WITH RECURSIVE ECOLI_GEN AS (
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT A.ID, A.PARENT_ID, G.GENERATION + 1 AS GENERATION
    FROM ECOLI_DATA A
    JOIN ECOLI_GEN G ON A.PARENT_ID = G.ID
)
SELECT ID
FROM ECOLI_GEN
WHERE GENERATION = 3
ORDER BY ID