-- 코드를 작성해주세요
SELECT ID,
    CASE WHEN A.P > 0.75 THEN 'LOW'
        WHEN A.P > 0.50 THEN 'MEDIUM'
        WHEN A.P > 0.25 THEN 'HIGH'
        ELSE 'CRITICAL'
    END AS COLONY_NAME
FROM (SELECT ID,
        PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) AS P
     FROM ECOLI_DATA) AS A
ORDER BY 1;