-- 코드를 작성해주세요
WITH RECURSIVE ECOLI_GEN AS (
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT D.ID, D.PARENT_ID, G.GENERATION + 1 AS GENERATION
    FROM ECOLI_DATA D
    JOIN ECOLI_GEN G
    ON D.PARENT_ID = G.ID
)
SELECT COUNT(E.ID) AS COUNT, G.GENERATION
FROM ECOLI_DATA E
JOIN ECOLI_GEN G
ON E.ID = G.ID
WHERE E.ID NOT IN (SELECT PARENT_ID FROM ECOLI_DATA WHERE PARENT_ID IS NOT NULL)
GROUP BY G.GENERATION
ORDER BY G.GENERATION