-- 코드를 입력하세요
WITH MAX_CATEGORY AS (SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
                     FROM FOOD_PRODUCT
                     WHERE CATEGORY IN ('과자', '국', '식용유', '김치')
                     GROUP BY CATEGORY)

SELECT F.CATEGORY, M.MAX_PRICE, F.PRODUCT_NAME
FROM FOOD_PRODUCT F
JOIN MAX_CATEGORY M
ON F.CATEGORY = M.CATEGORY
WHERE F.CATEGORY = M.CATEGORY AND F.PRICE = M.MAX_PRICE
ORDER BY F.PRICE DESC